config/routes.rb
Focus::Application.routes.draw do

  scope "(:locale)", :locale => Languages_regexp do

    root :to => 'home#index'

    get "search/index"
    get "search/search_home"

    match '/logout', :to => 'sessions#destroy'
    get '/sessions', :to => 'sessions#index'
    post '/sessions', :to => 'sessions#client_login'
    resource :session, :only => [:new, :create, :destroy]

    resources :moods, :only => [:new, :create, :edit, :update, :destroy, :index]

    post "comments/update"
    delete "comments/destroy"
    resources :comments, :only => [:create, :update, :destroy]

    post "users/create_contact"

    get "forms/send_view"
    get "forms/get_projects"
    get "forms/form_summary"
    get "forms/summary"
    get "forms/summary_token"
    get "forms/show_summary"
    post "forms/send_form"
    resources :forms, :only => [:new, :create, :destroy, :index]

    get "contents/modify_visibility"
    post "contents/update"
    post "contents/content_ranking"
    get "contents/show_all_comments"
    resources :contents, :only => [:create, :update, :destroy]

    resources :milestones, :only => [:create, :edit, :update, :destroy]

    get "projects/my_projects"
    get "projects/file"
    resources :projects, :only => [:show, :new, :create, :destroy, :index]

    get "clients/my_client"
    resources :clients

    get "contents/update"
    get "contents/show_add"
    get "contents/show_edit"
    get "users/edit_profile"
    get "users/activity_list"
    get "users/edit_contact"
    put "users/update_profile"
    put "users/update_contact"
    get "users/toggle_admin"
    get "users/update"
    get "users/new_contact"
    get "users/change_my_profile"
    match '/signup', :to => 'users#new'
    resources :users, :only => [:create, :show, :destroy, :index]

    get "set_mood/create"
    match '/set_mood', :to => 'set_mood#set_mood'
    match '/set_comment', :to => 'set_mood#set_comment'

    resources :password_resets, :only => [:new, :create, :edit, :update]
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :js

  before_filter :ensure_user
  before_filter :ensure_admin

  LIMIT = 8 # limite para el numero de consultas

  # Metodo que lista usuarios, clientes, proyectos que coinciden con la palabra buscada
  # Parametros de entrada: Palabra a buscar
  # Salida: Lista de usuarios, clientes y proyectos
  def index
    add_breadcrumb I18n.t('general.searcher'), :controller => "search", :action => "index"
    start = Time.now
    # Busca en usuarios
    @users = User.search(params[:search]) if params[:users]
    # Busca en clientes
		@clients = Client.search(params[:search]) if params[:clients]
		# Busca en proyectos
		@projects = Project.search(params[:search]) if params[:projects]
    # Busca en Contenidos
    @contents = Content.search(params[:search]) if params[:contents]

    @time = Time.now - start
  end

  def search_home
    # Busca en usuarios
    @users = User.search(params[:search_focus],LIMIT) || []
    # Busca en clientes
    @clients = Client.search(params[:search_focus],LIMIT) || []
    # Busca en proyectos
    @projects = Project.search(params[:search_focus],LIMIT) || []
    # Busca en Contenidos
    @contents = Content.search(params[:search_focus],LIMIT) || []

    @query = params[:search_focus]

    @limit = LIMIT
  end

end

app/helpers/search_helper.rb
require 'digest/md5'

module SearchHelper

  # Metodo que calcula la cantidad de resultados encontrados
  # Parametros de entrada: Tiempo, Lista de proyectos, clientes, usuarios y contenidos
  # Salida: Total de elementos encontrados
  def results(time,*args)
    total = args.inject(0){|a,s| a + (s && s.size || 0)}
    render :inline => I18n.t('search.result', :total => total.to_s, :time => time.round(4))
  end

  # Link para los users, para ser usada en la barra de búsqueda
  # Parámetros de entrada: Un usuario y el tamaño para la imagen
  # Salida: Una string conteniendo el link para ese usuario.
  def get_gravatar_url(user,size)
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "http://www.gravatar.com/avatar/#{hash}?size=#{size}"
  end

  # Parseo del resumen de un contenido, para ser mostrado en la barra de búsqueda.
  # Parámetros de entrada: Un string resumen y la query objetivo
  # Salida: Un string conteniendo el trozo del resumen a ser mostrado.
  def content_part(summary,query)
    q = query[0..24]
    len = 12 - q.length / 2
    match_data = summary.match(/^(.*?)?(.{0,#{len}}#{q}.{0,#{len}})(.*?)?$/i)
    ans = match_data[2]
    ans = '..' + ans if match_data[1] and !match_data[1].empty?
    ans += '..' if match_data[3] and !match_data[3].empty?
    ans
  end

end

app/views/search/_list.html.erb
<div class="row">
	<div class="span7 offset1">
		<h4> <small><%= results(@time,@projects, @clients, @users,@contents) %> </small></h4>
	</div>
</div>

<% if @users %>

  <div class="row">
    <div class="span5 offset1">
      <h3> <%= I18n.t('user.users') %> </h3>
    </div>
  </div>
    <% @users.each do |user| %>
  <div class="row fila-proyecto">
    <div class="span4 offset1">
      <div class="row nombre-contacto">
        <div class="span1">
          <%= get_gravatar(user,40) %>
        </div>
        <div class="span3">
          <strong>
          <%= link_to user.name , :controller => 'users', :action => 'show', :id => user.id %>
          </strong><br>
          <small><%= user.email %></small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>

<% if @clients %>

<section id="Clientes">
  <div class="row">
    <div class="span5 offset1">
      <h3><%= I18n.t('client.clients') %></h3>
    </div>
  </div>
<% @clients.all.each do |c| %>
    <div class="row fila-proyecto">
      <div class="span6 offset1">
        <div class="row cliente-proyecto-carita">
          <div class="span1">
             <%= image_client(c,:small) %>
          </div>
          <div class="span3 nombre-proyecto">
             <strong> <%= link_to c.name, c %> </strong>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</section>
<% end %>

<% if @projects %>

<section id="Proyectos">
  <div class="row">
    <div class="span5 offset1">
      <h3><%= t('project.projects')  %></h3>
    </div>
  </div>
  <%@projects.each do |project|%>
     <div class="row fila-proyecto">
      <div class="span6 offset1">
        <div class="row cliente-proyecto-carita">
          <div class="span1">
             <% mood = project.moods.last%>
          	 <%= show_mood(project)%>
          </div>
          <div class="span3 nombre-proyecto">
             <strong><%= link_to project.name, :controller => "projects", :action => "show", :id => project.id %></strong><br><span class="byClient">de</span> <a class="clientName" href="#"> <%= project.client_name %> </a>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</section>

<% end %>


<% if @contents %>

<section id="Proyectos">
  <div class="row">
    <div class="span5 offset1">
      <h3><%= t('content.content')  %></h3>
    </div>
  </div>
  <%@contents.each do |result|%>
     <div class="row fila-proyecto">
      <div class="span6 offset1">
        <div class="span1">
        	 <%=star_ranking_static(result)%>
        </div>
        <div class="span3 nombre-proyecto">
           <%= link_to result.summary, {:controller => 'contents', :action => 'show_all_comments',  :id => result.id} %> <%= t('general.in') %> <%= result.project.name%>
        </div>
      </div>
    </div>
  <%end%>
</section>

<% end %>

app/views/search/index.html.erb
<script>
function actualiza(str){
  $("#myform").trigger("submit.rails");
}
</script>

<div class="row">
  <div class="span7 offset1">
    <div class="row">
	  <form id='myform' action="/search/index" data-remote="true" method="get">  <p>
        <div class="input-append">
          <input id="search" value="<%=params[:search]%>" name="search" type="text" class="span7" placeholder="Buscar proyectos, clientes, etc." onkeyup="actualiza(this.value)">
          <span class="add-on"><i class="icon-search"></i></span>
        </div>
    </div>
  </div>
  <div class="span 3 offset1">
    <label class="checkbox">
      <input type="checkbox" value="" checked name="projects"> <%= I18n.t('general.project',:count => 2) %>
    </label>
    <label class="checkbox">
      <input type="checkbox" value="" checked name="users"> <%= I18n.t('user.users') %>
    </label>
    <label class="checkbox">
      <input type="checkbox" value="" checked name="clients"> <%= I18n.t('general.client',:count => 2) %>
    </label>
    <label class="checkbox">
      <input type="checkbox" value="" checked name="contents"> <%= I18n.t('content.content') %>
    </label>
  </div>
  </form>
</div>
<br>

<div id="aca">
  <%= render 'list' %>
</div>

app/views/search/index.js.erb
$('#aca').empty();
$('#aca').html("<%= escape_javascript(render 'list').html_safe %>");

app/views/search/search_home.js.erb
function order(a,b)
{
   var A = a.value.toLowerCase();
   var B = b.value.toLowerCase();
   if ( A < B ) return -1;
   if (A > B) return  1;
   return 0;
}

[
  <% @projects.each do |project| %>
    { id: <%= project.id %>, value: '<%= project.name %>', type: 'project', uri: '<%= project_path(project)  %>',extra: '<%= show_mood(project,:large).to_s.match(/src=\"([^\"]*)\"/)[1]%>'},
  <% end %>
  <% @clients.each do |client| %>
    { id: <%= client.id %>, value: '<%= client.name %>', type: 'client', uri: '<%= client_path(client)  %>', extra: '<%= client.image_file_name ? client.image.url(:big) : "/assets/missing_big.png" %>' },
  <% end %>
  <% @users.each do |user| %>
    { id: <%= user.id %>, value: '<%= user.name %>', type: 'user', uri: '<%= user_path(user)  %>', extra: '<%= get_gravatar_url(user,50) %>' },
  <% end %>
  <% @contents.each do |content| %>
    { id: <%= content.id %>, value: '<%= content_part(content.summary,@query) %>', type: 'content', uri: '<%= url_for(:controller => 'contents', :action => 'show_all_comments',  :id => content.id) %>', extra:'/assets/star-on-large.png' },
  <% end %>
].sort(order).slice(0,<%=@limit%>)