config/routes.rb
Focus::Application.routes.draw do

  scope "(:locale)", :locale => Languages_regexp do

    root :to => 'home#index'

    get "search/index"
    get "search/search_home"

    match '/logout', :to => 'sessions#destroy'
    get '/sessions', :to => 'sessions#index'
    post '/sessions', :to => 'sessions#client_login'
    resource :session, :only => [:new, :create, :destroy]

    resources :moods, :only => [:new, :create, :edit, :update, :destroy, :index]

    post "comments/update"
    delete "comments/destroy"
    resources :comments, :only => [:create, :update, :destroy]

    post "users/create_contact"

    get "forms/send_view"
    get "forms/get_projects"
    get "forms/form_summary"
    get "forms/summary"
    get "forms/summary_token"
    get "forms/show_summary"
    post "forms/send_form"
    resources :forms, :only => [:new, :create, :destroy, :index]

    get "contents/modify_visibility"
    post "contents/update"
    post "contents/content_ranking"
    get "contents/show_all_comments"
    resources :contents, :only => [:create, :update, :destroy]

    resources :milestones, :only => [:create, :edit, :update, :destroy]

    get "projects/my_projects"
    get "projects/file"
    resources :projects, :only => [:show, :new, :create, :destroy, :index]

    get "clients/my_client"
    resources :clients

    get "contents/update"
    get "contents/show_add"
    get "contents/show_edit"
    get "users/edit_profile"
    get "users/activity_list"
    get "users/edit_contact"
    put "users/update_profile"
    put "users/update_contact"
    get "users/toggle_admin"
    get "users/update"
    get "users/new_contact"
    get "users/change_my_profile"
    match '/signup', :to => 'users#new'
    resources :users, :only => [:create, :show, :destroy, :index]

    get "set_mood/create"
    match '/set_mood', :to => 'set_mood#set_mood'
    match '/set_comment', :to => 'set_mood#set_comment'

    resources :password_resets, :only => [:new, :create, :edit, :update]
  end

end

app/models/client.rb
class Client < ActiveRecord::Base

  attr_accessible :name, :language, :image, :contacts_attributes
  has_attached_file :image,
  	:styles => {
  		:big => "185x185#",
  		:small => "41x41>"}
  # Se define que clases estan relacionadas con el cliente y de que manera
  has_many :contacts, :autosave => false
  has_many :projects
  validate :email_not_repeated
  validate :skype_not_repeated

  validates :name,	:presence	=>	{ :message => 'client.validates_presence_name' },
  					        :uniqueness	=>	{ :message => 'client.validates_uniqueness_name' }
  validates :language, :presence =>  { :message => 'client.validates_language' }

  accepts_nested_attributes_for :contacts

  def email_not_repeated
    if self.contacts.map(&:email).uniq.length != self.contacts.size
      errors.add(:email, 'user.validates_repeated_email')
    end
  end

  def skype_not_repeated
    if self.contacts.map(&:skype).uniq.length != self.contacts.size
      errors.add(:skype, 'user.validates_repeated_skype')
    end
  end

  def send_set_mood_contacts(id_project)
    contacts.each do |item|
      setmood = SetMood.new
      setmood.add_user(item.id)
      setmood.add_project(id_project)
      setmood.send_set_mood
      setmood.save
    end
  end

  def self.search(search,num=nil)
    if search
      where('name LIKE ?',"%#{search}%").order('name asc').limit(num)
    end
  end

  def self.send_activity_list_to_all
    Client.all.each do |cli|
      cli.contacts.all.each do |cont|
        list = (Project.all + Comment.all + Content.all + Mood.all + Milestone.all)
        list.sort_by {|x| x[:updated_at]}
        ContactMailer.send_recent_activity(cont, cli, list).deliver
      end
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_filter :init, :except => [:my_client]
  before_filter :ensure_user
  before_filter :ensure_mooveit, :except => [:my_client]
  before_filter :ensure_admin, :only => [:new, :create]

  def init
    add_breadcrumb I18n.t('client.clients'), :controller => "clients", :action => "index"
  end

  # GET /clients
  # Metodo que muestra todos los clientes
  # Parametros de entrada: Ninguno
  # Salida: Lista de todos los clientes
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # Metodo que muestra la informacion de un cliente dado
  # Parametros de entrada: Id del cliente
  # Salida: Muestra la pagina show.html con toda la informacion del cliente
  def show
    # Busca el cliente por el id
    @client = Client.find(params[:id])
    add_breadcrumb @client.name, client_path(@client)
  end

  # GET /clients/new
  # Metodo que redirige a la pagina de creacion del nuevo cliente
  # Parametros de entrada: Ninguno
  # Salida: Pagina de creacion del cliente
  def new
    add_breadcrumb I18n.t('client.new'), :controller => "clients", :action => "new"
    # Se crea el cliente
    @client = Client.new
    @client.contacts.build
  end

  # GET /clients/1/edit
  # Metodo que redirige a la pagina de edicion de un cliente
  # Parametros de entrada: Id del cliente
  # Salida: Redirige a la pagina de edicion de los datos del cliente
  def edit
    # Se busca el cliente
    @client = Client.find(params[:id])
    add_breadcrumb @client.name, client_path(@client)
    add_breadcrumb I18n.t('client.edit'), :controller => "clients", :action => "edit", :id => @client.id
  end

  # POST /clients
  # Metodo que crea un cliente, y al menos, un contacto asociado a este
  # Parametros de entrada: Nombre, idioma, imagen asociada al cliente, y nombre, mail y skype de cada contacto que se quiera crear
  # Salida: Se crea el cliente y se redirige a la pagina del cliente creado
  def create
    # Se crea el cliente
    @client = Client.new(params[:client])
    # Se crean los contactos
    @client.contacts.each do |contact|
        contact.password = contact.name
        contact.language = params[:client][:language]
    end
    if @client.valid? and @client.contacts.map(&:valid?).all?
      # Se salva el cliente
      @client.save
      # Se salvan los contactos
      @client.contacts.each(&:save)
      redirect_to @client, flash: {success: I18n.t('client.create_success')}
    else
      render 'new'
    end
  end


  # PUT /clients/1
  # Metodo que actualiza los atributos de un cliente dado
  # Parametros de entrada: Id del cliente, y atributos a actualizar
  # Salida: Se redirige a la pagina del cliente cuyos datos fueron actualizados
  def update
    # Se busca el cliente
    @client = Client.find(params[:id])
    # Se actualizan los parametros
    if @client.update_attributes(params[:client])
      redirect_to @client, flash: {success: I18n.t('client.update_success')}
    else
      render 'edit'
    end
  end

  # DELETE /clients/1
  # Metodo que destruye un cliente dado
  # Parametros de entrada: Id del cliente
  # Salida: Se borra el cliente y se redirige a clients_url
  def destroy
    # Se busca el cliente
    @client = Client.find(params[:id])
    # Se destruye el cliente
    @client.destroy
    # Se redirige a clients_url
    redirect_to clients_url
  end

  # GET /my_client/1
  # Metodo que busca el cliente asociado a un contacto que se encuentra conectado
  # Parametros de entrada: Id del contacto conectado
  # Salida: Se redirige a la pagina del cliente asociado al contacto conectado
  def my_client
    # Se busca el cliente asociado al contacto
    @client = Client.find(current_user.client_id)
    add_current_to_breadcrumb @client.name
  end
end

app/helpers/clients_helper.rb
module ClientsHelper

  # Dado un cliente y un tamaño (:big o :small), esta funcion renderiza
  # la imagen del cliente en el tamaño correspondiente
  # Parametros de entrada: El cliente y el tamaño
  # Salida: Se renderiza la imagen
  def image_client(client,size)
    opts = size == :big ? {:class => "img-polaroid"} : {}
    if client.image_file_name
      image_src = image_tag client.image.url(size), opts
    else
      image_src = image_tag "missing_#{size.to_s}.png", opts
    end
    render :inline => image_src
  end

end

app/views/clients/_form.html.erb
<%= printErrors(client) %>

<div class="row">
  <%= form_for client, :url=> {:controller => 'clients', :action =>'create'}, :html => {:multipart => true, :class => "form-horizontal"} do |f|%>
  <div class="control-group">
    <label class="control-label" for="inputName"><%= t('general.name') %></label>
    <div class="controls">
      <%=f.text_field :name, :placeholder => "#{t('general.name')}"%>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputImage"><%= t('general.image') %></label>
    <div class="controls">
      <%=f.file_field :image %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><%= t('general.language') %></label>
    <div class="controls">
      <%= f.select(:language, options_for_select(language_opts, current_user.language)) %>
    </div>
  </div>

    <% it = 1 %>
    <%= f.fields_for :contacts do |builder| %>
  <div class="nuevo-contacto">
      <legend class="span4 offset1 contact-legend">
        <%= t('contact.contact') %> #<%= it %>
      </legend>
      <div class="clearfix">&nbsp;</div>
      <% it += 1 %>
    <div class="control-group">
      <label class="control-label" for="inputName"><%= t('general.name') %></label>
      <div class="controls">
        <%=builder.text_field :name, :placeholder => "#{t('general.name')}"%>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputEmail"><%= t('general.email') %></label>
      <div class="controls">
        <%=builder.text_field :email, :placeholder => "#{t('general.your')}@#{t('general.e_mail')}.com"%>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputEmail"><%= t('general.skype') %></label>
      <div class="controls">
        <%=builder.text_field :skype, :placeholder => "#{t('contact.skype')}"%>
      </div>
    </div>
  </div>
    <% end %>
    <div class="control-group span4 offset3 otro-contacto">
      <a class="btn btn-small" onclick="duplicateDiv();"><i class="icon-plus-sign"></i><%= t('contact.add_new') %></a>
    </div>
    <div class="clear-all">
    <div class="clearfix">&nbsp;</div>
    </div>
  <div class="control-group guardar-cliente">
    <div class="controls">
      <%= button_tag t('contact.create'), :value => "Crear Cliente", :type => :submit, :class=>"btn btn-large btn-inverse"%>
    </div>
  </div>
  <%end%> <!-- End of form -->
</div>

app/views/clients/edit.html.erb
<%= printErrors(@client) %>

<div class="row">
  <div class="span4 offset1">
    <h3>Edit <%= @client.name %></h3>
  </div>
</div>

<div class="row">
  <%= form_for @client, :url=> {:controller => 'clients', :action =>'update'}, :html => {:multipart => true, :class => "form-horizontal"} do |f|%>
  <div class="control-group">
    <label class="control-label" for="inputName"><%= t('general.name') %></label>
    <div class="controls">
      <%=f.text_field :name, :placeholder => "#{t('general.name')}"%>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputImage"><%= t('general.image') %></label>
    <div class="controls">
      <%=f.file_field :image%>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><%= t('general.language') %></label>
    <div class="controls">
      <%= f.select(:language, options_for_select(language_opts, @client.language)) %>
    </div>
  </div>
  <div class="control-group guardar-cliente">
    <div class="controls">
      <%= button_tag t('client.modify'), :type => :submit, :class=>"btn btn-large btn-inverse"%>
    </div>
  </div>
  <%end%>
</div>

app/views/clients/index.html.erb
<section id="Clientes">
  <div class="row">
    <div class="span5 offset1">
      <h3><%= I18n.t('client.clients') %> <%= link_to I18n.t('client.create') , new_client_path %></h3>
    </div>
  </div>
<% Client.all.each do |c| %>
    <div class="row fila-proyecto">
      <div class="span6 offset1">
        <div class="row cliente-proyecto-carita">
          <div class="span1">
             <%= image_client(c,:small) %>
          </div>
          <div class="span3 nombre-proyecto">
             <strong> <%= link_to c.name, c %> </strong>
          </div>
          <div class="span2 edit-element">
            <%= link_to I18n.t('general.edit'),{:controller => "clients", :action => "edit", :id => c.id },:class => "btn" %>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</section>

app/views/clients/my_client.html.erb
 <div class="row title-client">
    <div class="span2 offset1">
      <%= image_client(@client,:big) %>
    </div>

    <div class="span9">
      <h2> <%=@client.name%> </h2>
      <small><%=I18n.t("language.#{@client.language}")%></small>
    </div>
  </div>

	<%@client.projects.each do |project|%>

    <div class="row fila-proyecto">
      <div class="span4 offset1">
        <div class="row cliente-proyecto-carita">

          <div class="span1">
            <%= show_mood(project) %>
          </div>

          <div class="span3 nombre-proyecto">
            <strong><%= link_to project.name, :controller => "projects", :action => "show", :id => project.id %> </strong>
            <div class="span3">
            	<small><%= show_comment_mood(project)%></small>
          	</div>
          </div>

        </div>
      </div>
    </div>

  <%end%>

app/views/clients/new.html.erb
<%= javascript_include_tag "clients" %>
<div class="row">
	<div class="span4 offset1">
		<h3><%= t('client.new') %></h3>
	</div>
</div>

<%= render 'form', :client =>@client %>

app/views/clients/show.html.erb
  <div class="row title-client">
    <div class="span2 offset1">
      <%= image_client(@client,:big) %>
    </div>

    <div class="span9">
      <h2> <%=@client.name%> <small>(<%= link_to I18n.t('general.modify'), {:controller => "clients", :action => "edit", :id => @client.id} %>)</small></h2>
      <small><%= I18n.t("language.#{@client.language}")%></small>
    </div>
  </div>

  <div class="row">
    <div class="span5 offset1">
      <h3><%= I18n.t 'project.projects'%>  <%= link_to I18n.t('project.new'), new_project_path %></h3>
    </div>
  </div>

	<%@client.projects.each do |project|%>

    <div class="row fila-proyecto">
      <div class="span4 offset1">
        <div class="row cliente-proyecto-carita">

          <div class="span1 project-mood">
            <%= show_mood(project) %>
          </div>

          <div class="span3 nombre-proyecto">
            <strong><%= link_to project.name, project %></strong>
             <% if project.filed %>
              <small class="muted">Archivado</small>
             <% end %>
          </div>

        </div>
      </div>
      <% if !is_contact? && !project.filed %>
        <div class="span2 offset4">
          <%= link_to I18n.t('general.file'), {:controller => "projects", :action => "file", :id => project.id}, :class => "btn btn-danger pull-right" %>
        </div>
      <% end%>

    </div>

  <%end%>

  <div class="row">
    <div class="span5 offset1">
      <h3><%= I18n.t 'general.contacts' %> <% if !is_contact? %> <%= link_to I18n.t('contact.create'),:controller => "users", :action => "new_contact", :id => @client %> <%end%> </h3>
    </div>
  </div>

	<% @client.contacts.each do |c| %>
    <div class="row fila-proyecto">

      <div class="span6 offset1">
        <div class="row nombre-contacto">

          <div class="span1">
            <%= get_gravatar(c,40) %>
          </div>

          <div class="span3">
            <strong><%= link_to c.name, user_path(c) %></strong><br>
            <small><%= c.email %></small>
          </div>
          <div class="span2 edit-element">
            <%= link_to I18n.t('general.edit'), {:controller => "users", :action => "edit_contact", :id => c.id }, :class => "btn" %>
          </div>

        </div>
      </div>
      <div class="span2 offset2">
            <%= link_to I18n.t('general.destroy'), {:controller => 'users', :action => 'destroy', :id => c.id},:class => "btn btn-danger pull-right", :confirm => I18n.t('general.are_you_sure'), :method => :delete %>
      </div>
    </div>
<%end%>