config/routes.rb
Focus::Application.routes.draw do

  scope "(:locale)", :locale => Languages_regexp do

    root :to => 'home#index'

    get "search/index"
    get "search/search_home"

    match '/logout', :to => 'sessions#destroy'
    get '/sessions', :to => 'sessions#index'
    post '/sessions', :to => 'sessions#client_login'
    resource :session, :only => [:new, :create, :destroy]

    resources :moods, :only => [:new, :create, :edit, :update, :destroy, :index]

    post "comments/update"
    delete "comments/destroy"
    resources :comments, :only => [:create, :update, :destroy]

    post "users/create_contact"

    get "forms/send_view"
    get "forms/get_projects"
    get "forms/form_summary"
    get "forms/summary"
    get "forms/summary_token"
    get "forms/show_summary"
    post "forms/send_form"
    resources :forms, :only => [:new, :create, :destroy, :index]

    get "contents/modify_visibility"
    post "contents/update"
    post "contents/content_ranking"
    get "contents/show_all_comments"
    resources :contents, :only => [:create, :update, :destroy]

    resources :milestones, :only => [:create, :edit, :update, :destroy]

    get "projects/my_projects"
    get "projects/file"
    resources :projects, :only => [:show, :new, :create, :destroy, :index]

    get "clients/my_client"
    resources :clients

    get "contents/update"
    get "contents/show_add"
    get "contents/show_edit"
    get "users/edit_profile"
    get "users/activity_list"
    get "users/edit_contact"
    put "users/update_profile"
    put "users/update_contact"
    get "users/toggle_admin"
    get "users/update"
    get "users/new_contact"
    get "users/change_my_profile"
    match '/signup', :to => 'users#new'
    resources :users, :only => [:create, :show, :destroy, :index]

    get "set_mood/create"
    match '/set_mood', :to => 'set_mood#set_mood'
    match '/set_comment', :to => 'set_mood#set_comment'

    resources :password_resets, :only => [:new, :create, :edit, :update]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  attr_accessor :start_date, :end_date, :client_id

  attr_accessible :name, :description, :start_date, :end_date, :client_id

  validates :name,        :presence     => { :message => 'project.validates_name' },
                          :uniqueness   => { :message => 'project.validates_uniqueness' }
  validates :description, :presence     => { :message => 'project.validates_description' }
  validates :client_id,   :presence     => { :message => 'project.validates_client' }
  validates :start_date,  :presence     => { :message => 'project.validates_start_date' }
  validates :end_date,    :presence     => { :message => 'project.validates_end_date' }
  validate :valid_date?, :on => :create


  delegate :name, :to => :client, :prefix => true

  has_many :milestones
  has_many :moods
  has_many :contents

  belongs_to :client

  before_save :add_milestones, :add_client

  before_destroy :delete_contents, :delete_moods, :delete_milestones

  def add_client
    client = Client.find(client_id)
    self.client = client
    client.save
  end

  def add_milestones
  	start_milestone = Milestone.new :date => start_date,
  									                :name => I18n.t('project.milestone_start_name'),
  									                :description => I18n.t('project.milestone_start_desc')
    self.milestones << start_milestone
  	end_milestone = Milestone.new :date => end_date,
                								  :name => I18n.t('project.milestone_end_name'),
                								  :description => I18n.t('project.milestone_end_desc')
  	self.milestones << end_milestone
  end

  def valid_date?
    if self.end_date and self.start_date
      d1 = Date.strptime(self.end_date, "%d-%m-%Y")
      d2 = Date.strptime(self.start_date, "%d-%m-%Y")
      unless ( d1 > d2 )
        errors.add(:end_date, I18n.t('project.validates_end_date_after_start_date'))
      end
    end
  end

  def delete_contents
    self.contents.destroy_all
  end

  def delete_moods
    self.moods.destroy_all
  end

  def delete_milestones
    self.milestones.destroy_all
  end

  def self.search(search,num=nil)
    if search
      where('name LIKE ?',"%#{search}%").order('name asc').limit(num)
    end
  end

  def self.send_set_mood_to_all
    Project.all.each do |item|
      if !item.filed
        last_mood = Mood.find_last_by_project_id(item.id)
        if last_mood.nil?
          item.client.send_set_mood_contacts(item.id)
        else
          if last_mood.created_at < 7.days.ago
            item.client.send_set_mood_contacts(item.id)
          end
        end
      end
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :init
  before_filter :ensure_user
  before_filter :ensure_admin, :only => [:new, :create]
  before_filter :ensure_mooveit, :only => [:index] # contactos deberian usar my_projects
  before_filter :ensure_project_access, :only => [:show,:file]

  # Agrega el breadcrumb del indice de proyectos
  def init
    if current_user.instance_of? Contact
      add_breadcrumb I18n.t('project.list'), :action => "my_projects"
    else
      add_breadcrumb I18n.t('project.list'), :action => "index"
    end
  end

  # GET /projects
  # Metodo que lista los proyectos
  # lista todos los proyectos, para usuarios mooveit
  # Parametros de entrada: Ninguno
  # Salida: Lista de proyectos, contenida en la variable @projects
  def index
    # Lista todos los proyectos
    @projects = Project.all
  end

  # GET /projects/1
  # Metodo que muestra toda la informacion acerca de un proyecto dado, pasado por parametro
  # Parametros de entrada: Id del proyecto
  # Salida: Muestra todos los datos asociados al proyecto
  def show
    @focus_tab=params[:tab]
    # Se fija si hay que mostrar una tab especial al hacer el show,
    # sino, muestra la primera
    if @focus_tab== nil
      @focus_tab='1'
    end
    # Busca el proyecto por el id y lo muestra
    @project = Project.find(params[:id])
    # Agrega el breadcrumb con el nombre del proyecto
    add_breadcrumb @project.name, project_path(@project)
  end

  # GET /projects/new
  # Metodo que muestra la pagina new de proyecto, para poder crear un proyecto nuevo
  # Parametros de entrada: Ninguno
  # Salida: Pagina new de proyecto
  def new
    # Agrega el breadcrumb de la pagina new de proyecto
    add_breadcrumb I18n.t('project.new'), :controller => "projects", :action => "new"
    @project = Project.new
  end

  # POST /projects
  # Metodo que crea un proyecto nuevo
  # Parametros de entrada: nombre del proyecto, id del cliente asociado al proyecto, descripcion,
  #                        fecha de inicio, fecha de fin del proyecto
  # Salida: Se crea el proyecto y se redirige a la pagina show del proyecto creado
  def create
    @project = Project.new(params[:project])
    # Si se crea correctamente, se guarda y se redirige al show con un mensaje de exito,
    # sino, se hace un render al new del proyecto, dando el mensaje de error correspondiente
      if @project.save
        redirect_to @project, flash: {success: I18n.t('project.create_success')}
      else
        render 'new'
      end
  end

  # DELETE /projects/1
  # Metodo que borra un proyecto dado
  # Parametros de entrada: Id del proyecto
  # Salida: Se redirige projects_url
  def destroy
    # Se busca el proyecto por el id
    @project = Project.find(params[:id])
    # Se destruye
    @project.destroy
    redirect_to projects_url
  end

  # Metodo que muestra todos los proyectos del cliente asociado al usuario actual
  # Parametros de entrada: Id del cliente asociado al usuario actual
  # Salida: Lista todos los proyectos del cliente
  def my_projects
    @projects = Project.where(:client_id => current_user.client_id)
  end

  # Metodo que archiva un proyecto dado
  # Parametros de entrada: Id del proyecto a archivar
  # Salida: Se redirige a la pagina index de proyectos con un mensaje de exito
  def file
    # Se busca el proyecto
    @project = Project.find(params[:id])
    # Se archiva, seteandole un atributo del mismo en true
    @project.update_column(:filed, true)
    redirect_to :back, flash: {success: t('project.filed')}
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  # Metodo que muestra en la pagina show del proyecto, el estado de animo actual en tamaño grande
  # Parametros de entrada: El proyecto a mostrar
  # Salida: Se muestra la imagen correspondiente al ultimo estado de animo seteado por el cliente
  def show_mood(project,large=nil)
    # Se busca el ultimo estado de animo seteado por el cliente
    mood = Mood.find(:last, :conditions => {:project_id => project.id} )
    # Si nunca se seteo un estado de animo, se muestra el contento
    if !mood
      face = 'happy'
    else
      face = mood.mood
      face = face.downcase
    end
    # Se muestra en el show.html el estado de animo
    render :inline => '<img src="/assets/' + face + (large == :large ? '-lrg' : '') + '.png " title="' + I18n.t("mood."+face) + '" alt="' + I18n.t("mood."+face) + '" />'
  end

  # Metodo que muestra en la pagina show.html del proyecto, el comentario asociado al ultimo estado de animo seteado por el cliente
  # Parametros de entrada: El proyecto a mostrar
  # Salida: Se muestra el texto correspondiente al comentario del ultimo estado de animo
  def show_comment_mood(project)
    # Se busca el ultimo estado de animo seteado para el proyecto a mostrar
    mood = Mood.find(:last, :conditions => {:project_id => project.id} )
    # Si existe y no es vacio, se muestra dicho comentario
    if mood and (mood.comment != "")
      render :text => mood.comment
    end
  end

  # Muestra los contenidos del proyecto en la pagina show.html.
  # Para cada contenido se ve si el usuario actual es contacto, moove-it o administrador para ver cual de estos listar;
  # ya que los contenidos tienen un parametro de filtro de contenidos
  # Parametros de entrada: El proyecto a mostrar
  # Salida: La lista de contenidos dependientes del tipo de usuario
  def contents(project)
    # Se crea un hash de condiciones para hacer la busqueda de contenidos
    cond = Hash[:project_id => project.id]
    # Se obtiene el usuario conectado
    us = User.find(session[:user_id])
    # Si es contacto se setea la condicion de acceso a clientes
    cond[:access_client] = true if us.class == Contact
    # Si es administrador se setea la condicion de acceso a administrador o usuario moove-it
    cond[:access_moove_it] = true if us.class != Contact and !us.is_admin
    # Se buscan los contenidos, asociados al proyecto dado, que cumples las condiciones dadas anteriormente
    Content.find(:all, :conditions => cond, :order => 'created_at desc')
  end

  # Metodo que muestra la grafica de evolucion de estados en funcion del tiempo
  # Paramentros de entrada: Ninguno
  # Salida: Muestra la grafica en la pagina show.html del proyecto
  def show_chart
    render :partial => 'charts', :project => @project
  end

  def show_moods(project)
    total_moods = project.moods.count + 1
    images = ['happy','satisfied','neutral','sad','angry']
    total = images.map{|s| project.moods.where(:mood => s).count}
    total[0] += 1

    view=""
    5.times do |i|
      percentage = (total[i]* 100)/total_moods
      case percentage
      when 1...33
        view+='<img src="/assets/' + images[i]+ '-sml.png " title="' + images[i]+ '" alt="' + images[i]+ '" /> <br/><br/>'
      when 33...66
        view+='<img src="/assets/' + images[i]+ '.png " title="' + images[i]+ '" alt="' + images[i]+ '" /> <br/></br/>'
      when 66..100
        view+='<img src="/assets/' + images[i]+ '-lrg.png " title="' + images[i]+ '" alt="' + images[i]+ '" /> <br/><br/>'
      end
    end
    render :inline => view
  end

end

app/views/projects/_charts.html.erb
<script type="text/javascript">
  $(function() {
    new Highcharts.Chart({
      colors: ["#DDDF0D", "#7798BF", "#55BF3B", "#DF5353", "#aaeeee", "#ff0066", "#eeaaee", "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
      chart: {
        renderTo: "chart",
        height: 300,
        width: 600,
        backgroundColor: {
          linearGradient: [0, 0, 0, 400],
          stops: [
            [0, "rgb(96, 96, 96)"],
            [1, "rgb(16, 16, 16)"]
          ]
        },
        borderWidth: 0,
        borderRadius: 15,
        plotBackgroundColor: null,
        plotShadow: false,
        plotBorderWidth: 0
      },
      title: {
        text: "Evolucion del proyecto",
        style: {
          color: "#999",
          fontWeight: "bold"
        }
      },
      xAxis: {
        gridLineWidth: 0,
        lineColor: "#999",
        tickColor: "#999",
        labels: {
          style: {
            color: "#999",
            fontWeight: "bold"
          }
        },
        type: "datetime"
      },
      yAxis: {
        alternateGridColor: null,
        minorTickInterval: null,
        gridLineColor: "rgba(255, 255, 255, .1)",
        lineWidth: 0,
        tickWidth: 0,
        min:0,
        max:4,
        labels: {
          style: {
            color: "#999",
            fontWeight: "bold"
          }
        },
        title: {
          style: {
            color: "#AAA",
            font: "bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif"
          }
        },
        title: {
          text: "Estados de animo"
        },
        categories: ["Enojado", "Triste", "Neutral","Contento", "Feliz"]
      },
      legend: {
        itemStyle: {
          color: "#CCC"
        },
        itemHoverStyle: {
          color: "#FFF"
        },
        itemHiddenStyle: {
          color: "#333"
        }
      },
      labels: {
        style: {
          color: "#CCC"
        }
      },
      tooltip: {
        backgroundColor: {
          linearGradient: [0, 0, 0, 50],
          stops: [
            [0, "rgba(96, 96, 96, .8)"],
            [1, "rgba(16, 16, 16, .8)"]
          ]
        },
        borderWidth: 0,
        style: {
          color: "#FFF"
        }
      },
      plotOptions: {
        line: {
          dataLabels: {
            color: "#CCC"
          },
          marker: {
            lineColor: "#333"
          }
        },
        spline: {
          marker: {
            lineColor: "#333"
          }
        },
        scatter: {
          marker: {
            lineColor: "#333"
          }
        },
        candlestick: {
          lineColor: "white"
        }
      },
      series: [{
        name: "Estados",
        data: [[Date.UTC(<%= @project.created_at.strftime("%Y, %m-1, %d")%>), 4]
        <% @project.moods.each do |m|%>
          ,[Date.UTC(<%=m.created_at.strftime("%Y, %m-1, %d, %H")%>), <%=m.mood_number%>]
        <%end%>]
      }]
    });
  });
</script>

app/views/projects/_form.html.erb
  <% if project.errors.any? %>
    <%= printErrors(project) %>
  <% end %>

  <div class="row">
    <%= form_for project, :url=> {:controller => 'projects', :action =>'create'}, :html => { :class => "form-horizontal"} do |f|%>
    <div class="control-group">
      <label class="control-label">
        <%=  t('general.name') %>
      </label>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">
        <%=  t('general.client', :count => 1)%>
      </label>
      <div class="controls">
        <%= f.collection_select( :client_id, Client.all, :id, :name, options = { :prompt => "#{t('project.select_client')}" } ) =%>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" >
      <%=  t('general.description') %>
      </label>
      <div class="controls">
        <%= f.text_area :description, :size => "3" %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">
        <%=  t('date.start') %>
      </label>
      <div class="controls">
        <%fechaAux = Date.current%>
        <div class="input-append date focus-datepicker" id="input-inicio" data-date=<%=fechaAux.strftime("%d-%m-%Y")%> data-date-format="dd-mm-yyyy">
          <%= f.text_field :start_date, :class => "span2",  :readonly=>"readonly", :value => fechaAux.strftime("%d-%m-%Y")%>
          <span class="add-on"><i class="icon-th"></i></span>
        </div>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">
        <%= t('date.end') %>
      </label>
      <div class="controls">
        <%fechaAux = Date.current + 1%>
        <div class="input-append date focus-datepicker" id="input-fnicio" data-date=<%=fechaAux.strftime("%d-%m-%Y")%> data-date-format="dd-mm-yyyy">
          <%= f.text_field :end_date, :class => "span2", :readonly=>"readonly", :value => fechaAux.strftime("%d-%m-%Y")%>
          <span class="add-on"><i class="icon-th"></i></span>
        </div>
      </div>
    </div>

    <div class="control-group guardar-cliente">
      <div class="controls">
      <%= button_tag t('project.new'), :type => :submit, :class=>"btn btn-large btn-inverse"%>
      </div>
    </div>

<% end %>
  </div>

app/views/projects/edit.html.erb
<h1><%= t('project.edit') %></h1>

<%= render 'form' %>

<%= link_to t('general.show'), @project %> |
<%= link_to t('general.back'), projects_path %>

app/views/projects/index.html.erb
<div class="row">
  <div class="span4 offset1">
    <h3><%= I18n.t 'project.list'%> <%= link_to I18n.t('project.new'), new_project_path %></h3>
  </div>
</div>

<% @projects.each_slice(3) do |slice| %>
  <div class="row project-row">
  <% slice.each do |project| %>
    <div class="span4">
      <div class="row project-face">
        <div class="span1">
          <%= show_mood project %>
        </div>
        <div class="span3">
          <strong>
            <%= link_to project.name, project %>
          </strong>
          <br>
          <span class="byClient"><%= I18n.t "project.from" %></span>
          <%= link_to project.client_name, project.client, :class => "clientName"%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<% end %>
<br />

app/views/projects/my_projects.html.erb
<section id="Proyectos">
  <div class="row">
    <div class="span4">
      <h3><%= t('project.projects') %></h3>
    </div>
  </div>
  <div class="row project-row">
    <% contador = 0 %>
    <%@projects.each do |project|%>
    <div class="span4">
      <div class="row project-face">
        <div class="span1">
          <% mood = project.moods.last%>
          <%= show_mood(project)%>
        </div>
        <div class="span3">
          <strong><%= link_to project.name, :controller => "projects", :action => "show", :id => project.id %></strong><br><span class="byClient">de</span> <a class="clientName" href="#"> <%= project.client_name %> </a>
        </div>
      </div>
    </div>
    <% contador = contador + 1
        if contador == 3
          contador = 0 %>
          <br><br><br>
        <% end %>
    <% end %>
  </div>
</section>

app/views/projects/new.html.erb
<%= javascript_include_tag "projects" %>
<div class="row">
	<div class="span4 offset1">
		<h3><%= t('project.new') %></h3>
	</div>
</div>

<%= render 'form', :project =>@project %>

app/views/projects/show.html.erb
<%= printErrors(@project) %>

<div class="row">
  <%= render :partial => 'moods/show' %> <!-- View Mood -->
  <div class="span6 project-header">
    <div class="row">
      <div class="span6">
        <h2><%= @project.name %></h2>
        <span><%= @project.client_name %></span><br/>
        <small><%= @project.description %></small>
      </div>
      <div class="mood-project">
        <% if @project.moods != [] %>
          <%= @project.moods.last.comment %>
        <% end %>
      </div>
    </div>
  </div>
  <%if current_user.is_admin? and !@project.filed %>
    <div class="span4">
      <%= link_to I18n.t('set_mood.button'), {:controller => "set_mood", :action => "create", :id_project => @project.id}, :class => "btn btn-success set-mood-email", :type => "button" %>
    </div>
  <%end%>
</div>
<br/>
<div class="span12">
  <ul class="nav nav-tabs">
    <li
      <% if @focus_tab== "1" %>
        <%= "class=active" %>
      <% end %>
     ><a href="#tabs1-pane1" data-toggle="tab"><%= t('project.blackboard') %></a>
    </li>
    <li
      <% if @focus_tab == "2" %>
        <%= "class=active" %>
      <% end %>
      ><a href="#tabs1-pane2" data-toggle="tab"><%= t('milestone.milestones') %></a>
    </li>
    <li
      <% if @focus_tab == "3" %>
        <%= "class=active" %>
      <% end %>
      ><a href="#tabs1-pane3" data-toggle="tab"><%= t('project.statistics') %></a>
    </li>
  </ul>


  <div class="message_box">
    <% flash.each   do |name, msg| %>
      <% if name.to_s == "project_success"  %>
        <div class="message">
            <div class="alert alert-success">
                     <button class="close" data-dismiss="alert" type="button">x</button>
              <%= content_tag :div, msg%>
            </div>
        </div>
      <% end %>

      <% if name.to_s == "project_error"  %>
       <div class="message">
            <div class="alert alert-error">
                     <button class="close" data-dismiss="alert" type="button">x</button>
              <%= content_tag :div, msg%>
            </div>
        </div>
      <% end %>

    <% end %>
  </div>




  <div class="tab-content">
      <!-- ********* BLACKBOARD'S TAB ********* -->
      <% if @focus_tab== "1" %>
      <div class="tab-pane active" id="tabs1-pane1">
      <%else %>
       <div class="tab-pane" id="tabs1-pane1">
      <% end %>
        <% if !@project.filed %>
          <div id="flip2" class="offset2">
            <%if current_user.is_admin? || current_user.type == "Contact" %>
              <a class="btn btn-small"><%= t('content.add') %> <i class="icon-plus-sign"></i></a>
            <% end %>
          </div>
        <% end %>
        <div class="clearfix">&nbsp;</div>
        <div id="panel2" class="offset2">
          <%= render :partial => 'contents/show_add', :prev => @content %> <!-- Add content -->
        </div>
        <% contents(@project).each do |x| %>
          <div id ="panel-Modificar" class = "offset2" style="display:none">
            <%= render :partial => 'contents/show_edit', :locals => {:x => x, :errors => false} %> <!-- Modify content -->
          </div>
          <div class="row contenido-row">
            <%= render :partial => 'contents/show', :locals => {:x => x, :p => @project} %> <!-- View content -->
            <div class="separator"></div>
            <div class="span6 offset4">
              <%= render :partial => 'comments/show', :locals => {:x => x, :p => @project, :all => false} %> <!-- View comment -->
              <hr />
              <% if !@project.filed %>
                <%= render :partial => 'comments/new', :locals => {:x => x} %> <!-- Add comment -->
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <!-- ********* MILESTONES'S TAB ********* -->
      <% if @focus_tab== "2" %>
      <div class="tab-pane active" id="tabs1-pane2">
      <%else %>
      <div class="tab-pane" id="tabs1-pane2">
      <% end %>
        <div class="row">
          <% if !@project.filed %>
            <div id="flip3" class="offset2">
              <%if current_user.is_admin? %>
              <a class="btn btn-small"><%= t('milestone.add') %> <i class="icon-plus-sign"></i></a>
              <% end %>
            </div>
          <% end %>
          <div class="clearfix">&nbsp;</div>
          <div id="panel3" class="span9 offset2">
            <%= render :partial => 'milestones/form' %> <!-- Add milestone -->
          </div>
          <div>
            <%= render :partial => 'milestones/show', :locals => {:p => @project} %> <!-- View milestones -->
          </div>
        </div>
      </div>
      <!-- ********* STATISTICS'S TAB ********* -->
           <% if @focus_tab== "3" %>
      <div class="tab-pane active" id="tabs1-pane3">
      <%else %>
      <div class="tab-pane" id="tabs1-pane3">
      <% end %>
      <%= javascript_include_tag "highcharts" %>
  	  </br>
	  <div class="row">
	  	<div class="span7 offset1">
	  		<div class="row">
	   			<div id="chart">
	       			<%=show_chart()%>
	       		</div>
	       	</div>
	     </div>
	   <div class="span 3 offset1" align="center">
	   	 <%=show_moods(@project)%>
	   </div>
	  </div>
	  <br />
    </div>
  </div>
</div>